### PR TITLE
Add styles endpoint & fix missing versions (500 => 404)

### LINKED ISSUE #1: Return 404 when no version matches the `version` query param
Right now it returns a 500.

### LINKED ISSUE #2: Add a new endpoint for the styles (with the new theme)
See https://github.com/CleverCloud/clever-components/issues/403

### PR DESCRIPTION
**Pull request by hsablonniere**
Fixes #1 #2

### CODE REVIEW

File: src/load-components.js [hunk 1]
```diff
@@ -1,36 +1,37 @@
...
 
 const CDN_HOST = 'https://components.clever-cloud.com';
+const JS = 'application/javascript';
 const ONE_YEAR = 365 * 24 * 60 * 60;
 
 const MAGIC_MODE_NAME = 'magic-mode';
 const MAGIC_MODE_VALUE = 'dont-use-this-in-prod';
 
-export async function handleLoadRequest ({ getQueryParam, getJson, sendResponse }) {
+export async function handleLoadComponentsRequest (httpApi) {
```
Comment (pdesoyres-cc) [inline src/load-components.js]: Why don't you still use object destructuring?
I am fine with using an `httpApi` variable (I like the naming btw) but maybe you could add some JSDoc

**Review by pdesoyres-cc — CHANGES_REQUESTED** [review]

File: src/load-styles.js [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+  const versionsList = await httpApi.fetch(`versions-list.json`, CDN_HOST);
+  if (versionsList == null) {
+    return httpApi.sendResponse({ body: '', status: 500 });
+  }
+
+  const version = getVersion(versionsList, httpApi.getQueryParam('version'));
+
+  const depsManifest = await httpApi.fetch(`deps-manifest-${version.resolved}.json`, CDN_HOST);
+  if (depsManifest == null) {
+    return httpApi.sendResponse({ body: '', status: 500 });
```
Comment (pdesoyres-cc) [inline src/load-styles.js]: When depsManifest is null, could we have a distinction between:
* I can't fetch the response because of network issue
* I can't fetch the response because the version you're asking is not present

The latter would maybe conduct to sending a 404 with "Uknown version X.Y.Z" as body.

**Review by pdesoyres-cc — CHANGES_REQUESTED** [review]

File: src/load-styles.js (hunk 2 above)
Comment (pdesoyres-cc) [reply src/load-styles.js]: In fact, you may already know if the version doesn't exist when `version.resolved` is `null`.

File: src/load-styles.js [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+  }
+
+  const response = await getResponse(version, depsManifest, httpApi);
+
+  return httpApi.sendResponse(response);
+}
+
+export async function getResponse (version, depsManifest, httpApi) {
+
+  if (version.resolved == null) {
```
Comment (pdesoyres-cc) [inline src/load-styles.js:26]: this will never happen since the `httpApi.fetch(`deps-manifest-${version.resolved}.json`, CDN_HOST)` at line 14 may have failed.

I would have sent a 404 status code instead of 400. From my point of view, the query is valid but there is no resource for the given parameters.

File: src/load-styles.js [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+    return {
+      status: 400,
```
Comment (pdesoyres-cc) [inline src/load-styles.js]: I would have sent a 404 status code instead of 400. From my point of view, the query is valid but there is no resource for the given parameters.

File: src/load-styles.js [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+
+  const versionComment = `/* VERSION: ${version.resolved} */`;
+
+  const headers = getHeaders({
+    type: CSS,
+    maxAge: (version.requested === version.resolved) ? ONE_YEAR : 0,
+  });
+
+  let stylesBlocks;
+  if (depsManifest.manifestVersion !== '2') {
```
Comment (pdesoyres-cc) [inline src/load-styles.js]: Maybe this should lead to a 404 error: the user is asking for a resource that doesn't exist for the specified version

File: src/load-styles.js [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+    stylesBlocks = ['/* No styles to load /*'];
+  }
+  else {
+    stylesBlocks = await Promise.all(depsManifest.styles.map((s) => {
+      console.log(s.path, CDN_HOST);
```
Comment (pdesoyres-cc) [inline src/load-styles.js]: Do you really want to keep this log?

File: src/common.js [hunk 7]
```diff
@@ -0,0 +1,29 @@
+import { maxSatisfying } from 'es-semver';
+
```
Comment (pdesoyres-cc) [inline src/common.js:2]: You could also add here the paths `load.js` and `style.css` which are used in Hapi `start-server.js` and Cloudflare `index.js`

File: src/load-styles.js [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+  return {
+    'content-type': type,
+    'access-control-allow-origin': '*',
+    'cache-control': `public,max-age=${maxAge}`,
+  };
+}
+
+export async function getResponse (version, depsManifest, httpApi) {
+
+  if (version.resolved == null) {
```
Comment (pdesoyres-cc) [inline src/load-styles.js]: this will never happen since the httpApi.fetch(``deps-manifest-${version.resolved}.json``, CDN_HOST) at line 14 may have failed

**Comment by pdesoyres-cc** [comment]
Maybe, the `README.md` file should explain the new `/style.css` URI

File: src/load-components.js (hunk 1 above)
Comment (hsablonniere) [reply src/load-components.js]: I guess it's because I changed the way I call this function, I went from something like this:

```js
handleLoadComponentsRequest({
  getQueryParam (name) { /* ... */ },
  fetch (path, origin, asText = false) { /* ... */ },
  sendResponse (response) { /* ... */ },
});
```

to something like this:

```js
const cloudflareHttpApi = {
  getQueryParam (name) { /* ... */ },
  fetch (path, origin, asText = false) { /* ... */ },
  sendResponse (response) { /* ... */ },
};

handleLoadComponentsRequest(cloudflareHttpApi);
```

It doesn't change anything but I guess I did it because of that.

:+1: I added some JSDoc.

File: src/load-styles.js (hunk 2 above)
Comment (hsablonniere) [reply src/load-styles.js]: Technically, if `version.resolved` is not null, it came from the `versions-list.json`, if it's in this list, a manifest must exist and if not it's a problem cause by us => 500.

But as you said, `version.resolved` could be null if no version from the `versions-list.json` match the version query param. In this case, we should issue a 404.

=> I decided not to fix this with this PR because we already have the bug and I want a member of the team (not me) to fix it. https://github.com/CleverCloud/clever-components-cdn/issues/1

File: src/load-styles.js (hunk 8 above)
Comment (hsablonniere) [reply src/load-styles.js]: You're 100% right, I guess I actually should fix #1 in this PR.

File: src/load-styles.js (hunk 4 above)
Comment (hsablonniere) [reply src/load-styles.js]: You're right :+1:

File: src/load-styles.js (hunk 6 above)
Comment (hsablonniere) [reply src/load-styles.js]: I 100% DOT NOT :laughing:

File: src/load-styles.js (hunk 5 above)
Comment (hsablonniere) [reply src/load-styles.js]: I wondered about that. I guess we could change this.

File: src/common.js (hunk 7 above)
Comment (hsablonniere) [reply src/common.js:2]: Wow, awesome idea :heart_eyes:

File: src/load-components.js (hunk 1 above)
Comment (hsablonniere) [reply src/load-components.js]: I added some JSDoc on the functions.

File: src/load-styles.js (hunk 4 above)
Comment (hsablonniere) [reply src/load-styles.js]: Done.

File: src/load-styles.js (hunk 2 above)
Comment (hsablonniere) [reply src/load-styles.js]: Forget what I said, I fixed it :+1:

File: src/load-styles.js (hunk 5 above)
Comment (hsablonniere) [reply src/load-styles.js]: Done

File: src/load-styles.js (hunk 6 above)
Comment (hsablonniere) [reply src/load-styles.js]: Removed

File: src/common.js (hunk 7 above)
Comment (hsablonniere) [reply src/common.js:2]: Done

Comment (hsablonniere) [reply src/common.js:2]: I added them to their respective files (not the common one).

File: src/load-styles.js (hunk 8 above)
Comment (hsablonniere) [reply src/load-styles.js]: Done

**Comment by hsablonniere** [comment]
> Maybe, the `README.md` file should explain the new `/style.css` URI

Done :wink:

File: README.md [hunk 9]
```diff
@@ -6,25 +6,30 @@ Small endpoint to serve Clever Cloud components dynamicly.
 
 The Clever Components is a collection of Web Components made by Clever Cloud.
 
-It's available as an [Node.js package](https://www.npmjs.com/package/@clevercloud/components).
+It's available as a [Node.js package](https://www.npmjs.com/package/@clevercloud/components).
 User can npm install the package and import the modules they need in their own site/app.
 
 It's also available via a dedicated smart CDN.
-The idea is to provide users a single plug-and-play system, so they can load the components they need with just one script tag:
+The idea is to provide users with a simple plug-and-play system, so they can load the components and the theme with a small snippet of code like this:
```
Comment (pdesoyres-cc) [inline README.md]: Should we really use the "simple" wording? ;-)

File: README.md [hunk 10]
```diff
@@ -6,25 +6,30 @@ Small endpoint to serve Clever Cloud components dynamicly.
...
-Those files are prepared by a specific Rollup build and published on cellar along with a JSON manifest (listing the dependencies).
+The most important part of this smart CDN system is to serve static JavaScript files (as ES modules) along with CSS files and SVG files.
+Those assets are prepared by a specific Rollup build and published on cellar along with a JSON manifest (listing the dependencies).
 
-This project is the dynamic entrypoint of the system.
-It is what is executed behind https://components.clever-cloud.com/load.js.
+This project provides the two dynamic entrypoints of the system:
 
-When you load this dynamic script:
+* One to load the scripts: https://components.clever-cloud.com/load.js.
```
Comment (pdesoyres-cc) [inline README.md]: The generated link will lead to a 404 error because no version is specified.
Should we encapsulate this inside backticks?

File: README.md [hunk 11]
```diff
@@ -6,25 +6,30 @@ Small endpoint to serve Clever Cloud components dynamicly.
...
+* and another one to load the styles: https://components.clever-cloud.com/styles.css.
```
Comment (pdesoyres-cc) [inline README.md]: same as above

File: test/load-styles.test.js [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+      }
+      if (path === 'assets/awesome-theme-22c9efe8.css') {
+        return ':host { --some-color: green }';
+      }
+    },
+  };
+
+  const fakeHttpApiError = {
+    fetch: async (path, host) => {
+      throw new Error('HTPT error');
```
Comment (pdesoyres-cc) [inline test/load-styles.test.js]: Typo: `HTPT` => `HTTP`

File: src/load-components.js [hunk 13]
```diff
@@ -1,36 +1,44 @@
...
 
-  const files = getFiles(depsManifest, getQueryParam('components'));
+  const files = getFiles(depsManifest, httpApi.getQueryParam('components'));
   const response = getResponse(version, translation, files);
 
-  return sendResponse(response);
+  return httpApi.sendResponse(response);
 }
 
 // Resolve latest possible version from versions list
```
Comment (pdesoyres-cc) [inline src/load-components.js]: There is a typo in line 63:
> // This funciton also lists the unknown IDs

**Review by pdesoyres-cc — CHANGES_REQUESTED** [review]
What does that mean if the `version` parameter is not specified?

* Is it a bad request format? then we should return a 400 error.
* Should we fall back to the last version?

What does that mean if the `lang` parameter is not specified?

* Is it a bad request format? then we should return a 400 error.
* Should we fall back to something? (Maybe something related to issue https://github.com/CleverCloud/clever-components-cdn/issues/5)

File: README.md (hunk 9 above)
Comment (hsablonniere) [reply README.md]: I thought a bout that :rofl: This was more of a marketing announcement than a documentation guide saying this is simple to understand :p I'll remove it :wink:

File: README.md (hunk 10 above)
Comment (hsablonniere) [reply README.md]: Yes, good idea.

Comment (hsablonniere) [reply README.md]: I could even remove the origin, and just put `/load.js` and `/styles.css`, WDYT?

Comment (pdesoyres-cc) [reply README.md]: Yes so there is no confusion at all

File: src/load-components.js [hunk 14]
```diff
@@ -61,7 +60,7 @@ export function getTranslation (depsManifest, lang) {
 // Resolve paths to load from list of component IDs (coma separated string)
 // If the i18n file is needed, its path is provided on `i18nPath` but won't be part of the list of `paths`
 // This funciton also lists the unknown IDs
```
Comment (pdesoyres-cc) [inline src/load-components.js]: typo

File: src/load-components.js [hunk 15]
```diff
@@ -1,51 +1,50 @@
...
   }
 
-  const translation = getTranslation(depsManifest, getQueryParam('lang'));
+  const translation = getTranslation(depsManifest, url.searchParams.get('lang'));
 
-  if (getQueryParam(MAGIC_MODE_NAME) === MAGIC_MODE_VALUE) {
+  if (url.searchParams.get(MAGIC_MODE_NAME) === MAGIC_MODE_VALUE) {
     const magicModeResponse = getMagicModeResponse(version.resolved, translation.lang);
-    return sendResponse(magicModeResponse);
+    return magicModeResponse;
```
Comment (pdesoyres-cc) [inline src/load-components.js]: you can inline that

File: src/load-components.js [hunk 16]
```diff
@@ -1,51 +1,50 @@
...
   }
 
-  const files = getFiles(depsManifest, getQueryParam('components'));
+  const files = getFiles(depsManifest, url.searchParams.get('components'));
   const response = getResponse(version, translation, files);
```
Comment (pdesoyres-cc) [inline src/load-components.js]: you can inline that

File: src/load-styles.js [hunk 17]
```diff
@@ -0,0 +1,83 @@
...
+    };
+  }
+
+  const depsManifest = await getFile(`deps-manifest-${version.resolved}.json`, CDN_HOST);
+  if (depsManifest == null) {
+    console.error(`Cannot fetch deps-manifest-${version.resolved}.json`);
+    return { status: 500, body: '' };
+  }
+
+  const response = await getResponse(version, depsManifest, getFile);
```
Comment (pdesoyres-cc) [inline src/load-styles.js]: we can inline that

File: test/load-components.test.js [hunk 18]
```diff
@@ -1,324 +1,226 @@
...
+
+    it('french', async () => {
+      const response = await testLoadComponents('9.0.0', 'fr', 'cc-toggle');
+      testResponse(response, 200, JS, MAX_AGE_ONE_YEAR);
+      expectLines(response.body, 1, 2).to.equal(`// LANG: fr`);
+    });
+
+    it('error 40x if lang cannot be found', async () => {
+      const response = await testLoadComponents('9.0.0', 'es', 'cc-toggle');
+      testResponse(response, 400, JS, MAX_AGE_ZERO);
```
Comment (pdesoyres-cc) [inline test/load-components.test.js]: resource asked is not available should lead to 404

**Review by pdesoyres-cc — CHANGES_REQUESTED** [review]
Really nice like that! :clap:

There must be a reason, but why did you copy `dedent.js` source instead of a dependency in `package.json`?

**Comment by hsablonniere** [comment]
Note: this PR is ready to be merged and shipped. We'll handle this in late august.

**Review by pdesoyres-cc — APPROVED** [review]

**Comment by pdesoyres-cc** [comment]
Don't forget to add documentation about the style endpoint in https://www.clever-cloud.com/doc/clever-components/?path=/docs/%F0%9F%93%8C-docs-how-to-load-components-via-smart-cdn--page (new PR to be done in the [clever-components repository](https://github.com/CleverCloud/clever-components))

**Review by pdesoyres-cc — APPROVED** [review]
